export enum SportsCategory {
  BASEBALL = 'Baseball',
  BASKETBALL = 'Koszykówka',
  BOXING = 'Boks',
  CS_GO = 'CS:GO',
  ESPORT = 'Esport',
  ESPORT_CS_GO = 'Esport CS:GO',
  FAME_MMA = 'FAME MMA',
  FOOTBALL = 'Piłka nożna',
  FOOTBALL_WORLD_CUP_2022 = 'Piłka nożna-MŚ 2022',
  FOOTBALL_WORLD_CUP_2022_STS = 'Mistrzostwa Świata 2022',
  HIGH_LEAGUE = 'High League',
  HOCKEY = 'Hokej',
  MIXED_MARTIAL_ARTS = 'Sztuki walki',
  MIXED_MARTIAL_SPORTS = 'Sporty Walki',
  SZTUKI_WALKI = 'Sztuki Walki',
  MMA = 'MMA',
  TENIS = 'Tenis',
  UFC = 'UFC',
  VOLLEYBALL = 'Siatkówka',
}
